// Generated by CoffeeScript 1.10.0
var Pannel;

Pannel = (function() {

  /* class to easyli hide/show pannel */
  function Pannel(pannelID, defaultDisplayValue) {
    this.defaultDisplayValue = defaultDisplayValue != null ? defaultDisplayValue : "block";

    /*
    @param pannelID : the id of the element to use as pannel
    @param @defaultDisplayValue : the value to use to show the element (block, inline, flex...)
     */
    this.pannel = document.getElementById(pannelID);
    if (this.pannel === void 0) {
      console.log("Error, no element found with id " + pannelID);
    }
    return;
  }

  Pannel.prototype.hide = function() {
    this.pannel.style.display = "none";
  };

  Pannel.prototype.show = function() {
    this.pannel.style.display = this.defaultDisplayValue;
  };

  Pannel.prototype.isVisible = function() {
    if (this.pannel.style.display !== "none") {
      return true;
    } else {
      return false;
    }
  };

  return Pannel;

})();
