// Generated by CoffeeScript 1.10.0

/* Different state for our state machine */
var Candidate, candidate, psychoTestState,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

psychoTestState = {
  TEST_READY: 1,
  TESTING: 2,
  DONE: 3
};

Candidate = (function() {

  /* Candidate manage both the psycho test and the fingerPrint scanner */
  function Candidate() {
    this.reset = bind(this.reset, this);
    this.endTest = bind(this.endTest, this);
    this.startTest = bind(this.startTest, this);
    this.state = psychoTestState.TEST_READY;
    this.testStartPannel = new Pannel("testStart");
    this.testStartPannel.show();
    this.testStartPannel.pannel.onclick = this.startTest;
    this.testMainPannel = new TestMainPannel((function() {}), this.endTest);
    this.testResultPannel = new InfoPannel("testResult", "flex");
    return;
  }

  Candidate.prototype.startTest = function() {

    /* transition */
    if (this.state === psychoTestState.TEST_READY) {
      this.testStartPannel.hide();
      this.testMainPannel.show();
      this.testMainPannel.init();
      this.state = psychoTestState.TESTING;
    }
  };

  Candidate.prototype.endTest = function() {

    /* transition */
    if (this.state === psychoTestState.TESTING) {
      this.testResultPannel.setText("Félicitation.<br>Votre taux de réussite est de " + (this.testMainPannel.resultMean * 100) + "% et votre temps de réaction moyen est de\n" + this.testMainPannel.timeMean + "ms");
      this.testResultPannel.setBackground("#ff0");
      this.testMainPannel.hide();
      this.testResultPannel.show();
      this.state = psychoTestState.DONE;
      setTimeout(this.reset, 10000);
    }
  };

  Candidate.prototype.reset = function() {

    /* transition */
    this.testStartPannel.show();
    this.testMainPannel.hide();
    this.testResultPannel.hide();
    this.state = psychoTestState.TEST_READY;
  };

  return Candidate;

})();

candidate = new Candidate();
